[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi = true

# by setting ffi to true, this means you are allowing to run commands directly on our machine
# it is recommended to mostly leave it off

#remappings to redirect the import of a package

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
